### ISSUE TITLE
Recursive and back ref'd checksums are not always properly fixed in one pass

### ISSUE THREAD

**Issue by nyetwurk** [nyetwurk/ME7Sum#7]
Checksum corrections that affect previously checked areas do not cause the previously checked area to be checksummed again.

Work around is to run ME7Sum two or more times (iteratively) on successive "fixed" files.

**Comment by nyetwurk** [comment]
f1aae29683f25a5e7abf450ba4bb7b3be8aea4aa should fix this once and for all.

**Comment by Rick-2022** [comment]
So i can learn something here me7sum does the checksum calculation and me7check confirms if its right or wrong

**Comment by nyetwurk** [comment]
me7check is a very very old program that may or may not do checks that me7sum does. There is no way of knowing for sure since it is closed source.
